# Generated by Django 4.0.1 on 2022-01-16 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='subdivision',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.subdivision', verbose_name='Подразделение'),
            preserve_default=False,
        ),
    ]
