# Generated by Django 4.0.1 on 2022-01-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_employe_subdivision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_of_employment',
            field=models.DateField(blank=True, help_text='В формате: 2022-01-17', null=True, verbose_name='Дата устройства на работу'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Должность'),
        ),
    ]
